name: Test build the site

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Info
        run: |
          echo ${{ github.ref }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: build calendar files
        run: |
          ./build.sh --edit-link=https://github.com/$GITHUB_REPOSITORY
          mv ./out/*.ics assets/calendars/
      - name: create posts
        run: |
          python _scripts/generate_posts/generate_posts.py
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@master   # Choose any one of the Jekyll Actions
        with:                                # Some relative inputs of your action
          token: ${{ secrets.GITHUB_TOKEN }}
          build_only: true
          
        
